// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'underscore', 'backbone'], function($, _, Backbone) {
    var ClientesRouter;
    return ClientesRouter = (function(_super) {

      __extends(ClientesRouter, _super);

      function ClientesRouter() {
        return ClientesRouter.__super__.constructor.apply(this, arguments);
      }

      ClientesRouter.prototype.routes = {
        '': "theAlert",
        'list': "theAlert"
      };

      ClientesRouter.prototype.list = function() {
        return console.log("abrir listagem");
      };

      return ClientesRouter;

    })(Backbone.SubRoute);
  });

}).call(this);
