// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'underscore', 'backbone', 'models/clientes'], function($, _, Backbone, Clientes) {
    var ClientesRouter;
    return ClientesRouter = (function(_super) {

      __extends(ClientesRouter, _super);

      function ClientesRouter() {
        return ClientesRouter.__super__.constructor.apply(this, arguments);
      }

      ClientesRouter.prototype.routes = {
        '': "listar",
        '/': "listar",
        'listar': "listar"
      };

      ClientesRouter.prototype.listar = function() {
        var clientes;
        clientes = new Clientes();
        return clientes.fetch({
          success: function() {
            return console.log(clientes);
          }
        });
      };

      return ClientesRouter;

    })(Backbone.SubRoute);
  });

}).call(this);
