// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'underscore', 'backbone', 'sprintf', 'views/appview', 'subroute'], function($, _, Backbone, sprintf, AppView) {
    var CoreController;
    return CoreController = (function(_super) {

      __extends(CoreController, _super);

      function CoreController() {
        this.handleError = __bind(this.handleError, this);
        return CoreController.__super__.constructor.apply(this, arguments);
      }

      CoreController.prototype.routes = {
        ":controller(/*path)": 'loadModuleRouter'
      };

      CoreController.prototype.subRouters = {};

      CoreController.prototype.initialize = function() {
        CoreController.__super__.initialize.call(this);
        this.setResponseCatchers();
        Backbone.history.start();
        return AppView.render().$el.appendTo("body");
      };

      CoreController.prototype.loadModuleRouter = function(controller) {
        var controllerName,
          _this = this;
        controller = controller.toLowerCase();
        controllerName = controller.substr(0, 1).toUpperCase() + controller.substr(1).toLowerCase();
        if (!(this.subRouters[controller] != null) && controller !== "core") {
          return require(["controllers/" + controller], function(Controller) {
            console.log(sprintf("Starting controller %1$s ...", controllerName));
            if (!(_this.subRouters[controller] != null) && controller !== "core") {
              return _this.subRouters[controller] = new Controller(controller);
            }
          });
        }
      };

      CoreController.prototype.handleError = function(error) {};

      CoreController.prototype.setResponseCatchers = function() {
        var _this = this;
        return $.ajaxSetup({
          statusCode: {
            401: function() {
              return _this.navigate("login", {
                trigger: true
              });
            }
          }
        });
      };

      return CoreController;

    })(Backbone.Router);
  });

}).call(this);
