// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'underscore', 'backbone', 'bootstrap', 'modules/core/router'], function($, _, Backbone, Bootstrap, Router) {
    var Core;
    return Core = (function(_super) {

      __extends(Core, _super);

      function Core() {
        return Core.__super__.constructor.apply(this, arguments);
      }

      Core.prototype.initialize = function() {
        var _this = this;
        this.router = new Router();
        Backbone.history.start();
        return Backbone.Events.on("load_view", function(PageView) {
          return _this.setPageView(PageView);
        });
      };

      return Core;

    })(Backbone.Model);
  });

}).call(this);
