// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'underscore', 'backbone', 'bootstrap', 'text!templates/skeleton.html'], function($, _, Backbone, Bootstrap, AppViewTemplate) {
    var AppView;
    AppView = (function(_super) {

      __extends(AppView, _super);

      function AppView() {
        return AppView.__super__.constructor.apply(this, arguments);
      }

      AppView.prototype.template = _.template(AppViewTemplate);

      AppView.prototype.title = "Carregando...";

      AppView.prototype.view = null;

      AppView.prototype.rendered = false;

      AppView.prototype.setView = function(title, view) {
        this.title = title;
        this.view = view;
        return this.render();
      };

      AppView.prototype.render = function() {
        if (!this.rendered) {
          this.$el.html(this.template({
            title: this.title
          }));
          this.rendered = true;
        }
        if (this.view != null) {
          this.$("#view").html(this.view.render().$el);
        }
        document.title = "" + this.title + " - Top Claro";
        this.$("#view-title").html(this.title);
        return this;
      };

      return AppView;

    })(Backbone.View);
    return new AppView();
  });

}).call(this);
