// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'underscore', 'backbone', 'bootstrap', 'text!templates/skeleton.html'], function($, _, Backbone, Bootstrap, AppViewTemplate) {
    var AppView;
    return AppView = (function(_super) {

      __extends(AppView, _super);

      function AppView() {
        return AppView.__super__.constructor.apply(this, arguments);
      }

      AppView.prototype.template = _.template(AppViewTemplate);

      AppView.prototype.render = function() {
        this.$el.html(this.template());
        return this;
      };

      return AppView;

    })(Backbone.View);
  });

}).call(this);
