// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'underscore', 'backbone', 'modules/core/router', 'bootstrap', 'text!templates/pages/skeleton.html'], function($, _, Backbone, Router, Bootstrap, SkeletonTemplate) {
    var Core;
    return Core = (function(_super) {

      __extends(Core, _super);

      function Core() {
        return Core.__super__.constructor.apply(this, arguments);
      }

      Core.prototype.template = _.template(SkeletonTemplate);

      Core.prototype.defaults = {
        "view": null,
        "sessao": false
      };

      Core.prototype.initialize = function() {
        var _this = this;
        this.router = new Router();
        Backbone.history.start();
        return Backbone.Events.on("load_view", function(PageView) {
          return _this.currentView = PageView;
        });
      };

      Core.prototype.render = function() {
        this.$el.html(this.template());
        return this;
      };

      Core.prototype.setPageView = function(PageView) {
        return this.view.$el.detach();
      };

      return Core;

    })(Backbone.View);
  });

}).call(this);
