// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['underscore', 'backbone', 'settings', 'models/endereco'], function(_, Backbone, Settings, Endereco) {
    var Enderecos;
    Enderecos = (function(_super) {

      __extends(Enderecos, _super);

      function Enderecos() {
        return Enderecos.__super__.constructor.apply(this, arguments);
      }

      Enderecos.prototype.initialize = function(items, options) {
        if (options.contato != null) {
          return this.contato = options.contato;
        }
      };

      Enderecos.prototype.url = function() {
        var base;
        base = this.contato != null ? "" + (this.contato.url()) : Settings.api.url;
        return base += "/telefones";
      };

      Enderecos.prototype.model = Endereco;

      return Enderecos;

    })(Backbone.Collection);
    return Enderecos;
  });

}).call(this);
