// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'underscore', 'backbone', 'models/contato', 'collections/contatos', 'text!templates/contatos/editor.html', 'backbone-forms-list', 'backbone-forms-inline-nestedmodels'], function($, _, Backbone, Contato, Contatos, ContatosEditorTemplate) {
    var ContatoEditorView;
    return ContatoEditorView = (function(_super) {

      __extends(ContatoEditorView, _super);

      function ContatoEditorView() {
        return ContatoEditorView.__super__.constructor.apply(this, arguments);
      }

      ContatoEditorView.prototype.className = 'modal fade';

      ContatoEditorView.prototype.template = _.template(ContatosEditorTemplate);

      ContatoEditorView.prototype.initialize = function(options) {
        if (!(this.model != null)) {
          this.model = new Contato();
        }
        return this.form = new Backbone.Form({
          model: this.model
        });
      };

      ContatoEditorView.prototype.render = function() {
        this.$el.html(this.template({
          contato: this.model.toJSON()
        }));
        this.$el.modal({
          keyboard: true,
          backdrop: true
        });
        this.$('.modal-body').html(this.form.render().el);
        return this;
      };

      return ContatoEditorView;

    })(Backbone.View);
  });

}).call(this);
