// Generated by CoffeeScript 1.4.0
(function() {

  requirejs.config({
    enforceDefine: true,
    shim: {
      backbone: {
        deps: ['underscore', 'jquery'],
        exports: 'Backbone'
      }
    },
    paths: {
      backbone: 'vendors/backbone',
      underscore: 'vendors/underscore',
      jquery: 'vendors/jquery'
    }
  });

  define(['jquery', 'underscore', 'backbone', ''], function($, _, Backbone) {
    var app;
    app = new Backbone.Router();
    return $.ajaxSetup({
      statusCode: {
        401: function() {
          return app.navigate("login", {
            trigger: true
          });
        },
        403: function() {
          return app.navigate("denied", {
            trigger: true
          });
        }
      }
    });
  });

}).call(this);
