// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'underscore', 'backbone', 'subroute'], function($, _, Backbone, App) {
    var AppRouter;
    AppRouter = (function(_super) {

      __extends(AppRouter, _super);

      function AppRouter() {
        return AppRouter.__super__.constructor.apply(this, arguments);
      }

      AppRouter.prototype.subRouters = {};

      AppRouter.prototype.routes = {
        ":module(/*path)": 'loadModuleRouter'
      };

      AppRouter.prototype.loadModuleRouter = function(module, subRoute) {
        var _this = this;
        if (!(this.subRouters[module] != null)) {
          return require(["modules/" + module + "/router"], function(SubRouter) {
            return _this.subRouters[module] = new SubRouter(module + "/");
          });
        }
      };

      return AppRouter;

    })(Backbone.Router);
    window.Router = new AppRouter();
    $.ajaxSetup({
      statusCode: {
        401: function() {}
      }
    });
    Router.navigate("login", {
      trigger: true,
      403: function() {}
    });
    Router.navigate("denied", {
      trigger: true
    });
    return Backbone.history.start();
  });

}).call(this);
