// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'underscore', 'backbone', 'settings', 'models/cliente'], function($, _, Backbone, Settings, Cliente) {
    var Clientes;
    return Clientes = (function(_super) {

      __extends(Clientes, _super);

      function Clientes() {
        return Clientes.__super__.constructor.apply(this, arguments);
      }

      Clientes.prototype.model = Cliente;

      Clientes.prototype.url = Settings["API_URL"] + "/clientes";

      Clientes.prototype.comparator = function(model) {
        return model.get("name");
      };

      Clientes.prototype.parse = function(response) {
        return response.data;
      };

      return Clientes;

    })(Backbone.Collection);
  });

}).call(this);
