// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'underscore', 'backbone', 'models/contato'], function($, _, Backbone, Contato) {
    var Cliente;
    return Cliente = (function(_super) {

      __extends(Cliente, _super);

      function Cliente() {
        return Cliente.__super__.constructor.apply(this, arguments);
      }

      return Cliente;

    })(Backbone.Model);
  });

}).call(this);
