// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['backbone'], function(Backbone) {
    var Email;
    Email = (function(_super) {

      __extends(Email, _super);

      function Email() {
        return Email.__super__.constructor.apply(this, arguments);
      }

      return Email;

    })(Backbone.Model);
    Email.schema = Email.prototype.schema = {
      identificacao: {
        type: "Text",
        title: "Rótulo"
      },
      email: {
        type: "Text",
        title: "E-mail"
      }
    };
    return Email;
  });

}).call(this);
