// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'underscore', 'backbone', 'views/appview', 'collections/contatos', 'views/contatos/index', 'views/contatos/editor'], function($, _, Backbone, AppView, Contatos, ContatosIndexView, ContatoEditorView) {
    var ContatosRouter, newRoute, routes;
    newRoute = __('NEW_CONTACT_ROUTE', 'novo');
    routes = {};
    routes["" + newRoute] = "new";
    routes[""] = "index";
    routes["/"] = "index";
    routes[":id"] = "edit";
    return ContatosRouter = (function(_super) {

      __extends(ContatosRouter, _super);

      function ContatosRouter() {
        return ContatosRouter.__super__.constructor.apply(this, arguments);
      }

      ContatosRouter.prototype.routes = routes;

      ContatosRouter.prototype.contatos = new Contatos();

      ContatosRouter.prototype.index = function() {
        if ((AppView.view != null) && AppView.view.constructor.name === "ContatosIndexView") {
          return;
        }
        AppView.setTitle("Contatos");
        return AppView.setView(new ContatosIndexView({
          collection: this.contatos
        }));
      };

      ContatosRouter.prototype["new"] = function() {
        var editor,
          _this = this;
        if (!AppView.view || (AppView.view != null) && AppView.view.constructor.name === !"ContatosIndexView") {
          AppView.setView(new ContatosIndexView({
            collection: this.contatos
          }));
        }
        editor = new ContatoEditorView();
        editor.$el.on("hidden", function() {
          return _this.navigate("" + _this.prefix + "/");
        });
        return editor.render();
      };

      ContatosRouter.prototype.edit = function() {};

      return ContatosRouter;

    })(Backbone.SubRoute);
  });

}).call(this);
